version: '3.8'
services:
  pgvector-db:
    image: ankane/pgvector
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  streamlit-app:
    build: ./src
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - pgvector-db
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: pgvector-db
      POSTGRES_PORT: 5432
    deploy:
      resources:
        limits:
          memory: 24G
        reservations:
          memory: 16G

volumes:
  pgvector_data:
